/**
 * ENGLISH UI TEXT — the app's copy, in one place.
 *
 * LOCALIZATION APPROACH (deliberately minimal for V1):
 *   Marathi is NOT implemented yet, but the seam exists. To add it later:
 *     1. Add `mr.ts` with the same shape (TypeScript enforces completeness
 *        via `satisfies Copy`).
 *     2. Change `useCopy()` in ./index.ts to select by active locale.
 *     3. No component changes required — they already read from `useCopy()`.
 *
 * SCOPE RULE: put SHARED and STRUCTURAL text here — navigation, actions,
 * states, statuses, common labels. Screen-specific prose stays with its screen
 * once that screen is built, so this file does not become a dumping ground.
 * Do not centralise every string at any cost; centralise what repeats.
 */
export const en = {
  app: {
    name: 'Mahakhanij',
    tagline: 'Consumer',
  },

  /** Bottom navigation labels. Role-driven — see @/navigation/tabs.ts */
  nav: {
    home: 'Home',
    projects: 'Projects',
    mineral: 'Mineral',
    inventory: 'Inventory',
    orders: 'Orders',
    enquiry: 'Enquiry',
    activity: 'Activity',
    report: 'Report',
    more: 'More',
  },

  /** Reusable action verbs. Keep short — these sit inside touch targets. */
  actions: {
    back: 'Back',
    cancel: 'Cancel',
    confirm: 'Confirm',
    continue: 'Continue',
    close: 'Close',
    clear: 'Clear',
    retry: 'Try again',
    search: 'Search',
    signOut: 'Sign out',
    viewAll: 'View all',
    change: 'Change',
  },

  /** Shared empty / loading / error copy. */
  states: {
    loading: 'Loading',
    emptyTitle: 'Nothing here yet',
    errorTitle: 'Something went wrong',
    errorDescription: 'We could not load this. Check your connection and try again.',
  },

  /** Organization → Project → Package context. */
  context: {
    project: 'Project',
    package: 'Package',
    noProjectSelected: 'No project selected',
    noPackageSelected: 'No package selected',
  },

  /** Recurring operational field labels. */
  fields: {
    mineral: 'Mineral',
    quantity: 'Quantity',
    vehicle: 'Vehicle',
    status: 'Status',
    location: 'Location',
    destination: 'Destination',
    source: 'Source',
    stockPoint: 'Stock point',
    distance: 'Distance',
    dispatchedQuantity: 'Dispatched quantity',
    receivedQuantity: 'Received quantity',
    difference: 'Difference',
    available: 'Available',
    received: 'Received',
    consumed: 'Consumed',
    supervisor: 'Supervisor',
    etpNumber: 'DigiTP number',
  },

  userType: {
    NORMAL_CONSUMER: 'Individual',
    ORGANIZATION: 'Organization',
  },

  organizationType: {
    BUILDER: 'Builder',
    CONTRACTOR: 'Contractor',
    GOVERNMENT: 'Government',
    OTHER: 'Organization',
  },

  /** Organization Home — the fixed section order from the product context. */
  organizationHome: {
    attentionRequired: 'Attention required',
    attentionClear: 'Nothing needs your attention',
    attentionClearBody: 'Deliveries, discrepancies and applications that need action will appear here.',
    businessOverview: 'Business overview',
    activeProjects: 'Active projects',
    activePackages: 'Active packages',
    activeOrders: 'Active orders',
    availableInventory: 'Available inventory',
    quickActions: 'Quick actions',
    findStockPoint: 'Find stock point',
    createEnquiry: 'All enquiry',
    receiveMineral: 'Receive mineral',
    activeDeliveries: 'Active deliveries',
    noActiveDeliveries: 'No deliveries in transit',
    noActiveDeliveriesBody: 'Vehicles on the way to your sites will appear here.',
    trackLive: 'Track live',
    receive: 'Receive',
    inventorySnapshot: 'Inventory snapshot',
    acrossActivePackages: 'Across active packages',
    temporaryExcavation: 'Temporary excavation',
    activeApplications: 'Active applications',
    needingAttention: 'Needing attention',
    viewApplications: 'View applications',
  },

  /** Projects → Project → Packages → Package. */
  projects: {
    title: 'Projects',
    noProjects: 'No projects yet',
    noProjectsBody: 'Projects assigned to your organization will appear here.',
    packages: 'Packages',
    packageCount: (count: number) => `${count} ${count === 1 ? 'package' : 'packages'}`,
    noPackages: 'No packages in this project',
    noPackagesBody: 'Packages will appear here once they are created.',
    projectDetails: 'Project details',
    packageDetails: 'Package details',
    site: 'Site',
    mineralOperations: 'Mineral operations',
    operationsHint: 'Everything below is scoped to this package.',
    supervisorNote: 'Assigned supervisor. Supervisors work in a separate app.',
    viewInventory: 'Inventory',
    viewOrders: 'Orders',
  },

  /** Mineral acquisition: Find Stock Point → Details → Enquiry. */
  discovery: {
    title: 'Find stock point',
    searchPlaceholder: 'Stock point, taluka or district',
    filters: 'Filters',
    listView: 'List',
    mapView: 'Map',
    mineral: 'Mineral',
    anyMineral: 'Any mineral',
    withinDistance: 'Within',
    anyDistance: 'Any distance',
    inStockOnly: 'In stock only',
    apply: 'Apply',
    clearAll: 'Clear all',
    resultCount: (count: number) => `${count} ${count === 1 ? 'stock point' : 'stock points'}`,
    noResults: 'No stock points match',
    noResultsBody: 'Try widening the distance or clearing a filter.',
    noDestination: 'Select a package first',
    noDestinationBody:
      'Stock points are ranked by distance from your site, so choose the package you are sourcing for.',
    chooseProject: 'Choose a project',
    availableMinerals: 'Available minerals',
    sourceQuarry: 'Source quarry',
    licence: 'Licence',
    operatingHours: 'Operating hours',
    contact: 'Contact',
    sendEnquiry: 'Send enquiry',
    away: 'away',
  },

  /** Enquiry — never "booking", never "checkout". */
  enquiry: {
    title: 'Mineral enquiry',
    listTitle: 'Enquiries',
    newEnquiry: 'New enquiry',
    requirement: 'Your requirement',
    selectMineral: 'Mineral',
    quantityLabel: 'Required quantity',
    requiredBy: 'Required by',
    requiredByHint: 'Optional. When you need it on site.',
    remarks: 'Remarks',
    remarksPlaceholder: 'Anything the stock point should know',
    submit: 'Send enquiry',
    submitting: 'Sending…',
    sentTitle: 'Enquiry sent',
    sentBody: 'The stock point has your requirement. You can follow it here.',
    viewEnquiry: 'View enquiry',
    noEnquiries: 'No enquiries yet',
    noEnquiriesBody: 'Find a stock point and send your first mineral enquiry.',
    findStockPoint: 'Find stock point',
    enquiryNumber: 'Enquiry number',
    raisedOn: 'Raised on',
    lastUpdated: 'Last updated',
    availableHint: (value: string) => `${value} currently available`,
  },

  /** Normal Consumer home. */
  consumerHome: {
    onTheWay: 'On the way',
    needMineral: 'Need mineral?',
    needMineralBody: 'Find a stock point near you and send an enquiry.',
    mineralAvailability: 'Mineral availability',
    nearestSource: 'Nearest source',
    notAvailable: 'Not available',
    viewStockPoints: 'View stock points',
    sourceCount: (count: number) => `${count} source${count === 1 ? '' : 's'}`,
    recentActivity: 'Recent activity',
    noActivity: 'Nothing yet',
    noActivityBody: 'Your enquiries and orders will appear here.',
    yourInventory: 'Your inventory',
    available: 'Available',
    unit: 'Unit',
  },

  /** Orders and transport. Tracking is operational, never a courier ETA. */
  orders: {
    title: 'Orders',
    noOrders: 'No orders yet',
    noOrdersBody: 'Orders created from your enquiries will appear here.',
    orderNumber: 'Order number',
    fromEnquiry: 'From enquiry',
    ordered: 'Ordered',
    dispatched: 'Dispatched',
    received: 'Received',
    pendingDispatch: 'Pending dispatch',
    awaitingReceipt: 'Awaiting receipt',
    dispatchStatus: 'Dispatch',
    receivingStatus: 'Receiving',
    deliveries: 'Deliveries',
    noDeliveries: 'No deliveries yet',
    noDeliveriesBody: 'Vehicles dispatched against this order will appear here.',
    placedOn: 'Placed on',
    shortReceived: 'short received',
  },

  tracking: {
    title: 'Vehicle tracking',
    driver: 'Driver',
    transporter: 'Transporter',
    lastUpdate: 'Last update',
    route: 'Route',
    source: 'Source',
    destination: 'Destination',
    transportPermit: 'Transport permit',
    permitNumber: 'DigiTP number',
    permittedQuantity: 'Permitted quantity',
    validUntil: 'Valid until',
    quarry: 'Quarry',
    movement: 'Movement',
    noUpdates: 'No movement recorded yet',
    noUpdatesBody: 'Location updates will appear here once the vehicle is dispatched.',
    receiveNow: 'Receive mineral',
    arrivedNote: 'This vehicle has arrived and is waiting to be received.',
    callDriver: 'Call driver',
  },

  /** Receiving — the destination-side verification of a transport permit. */
  receiving: {
    title: 'Receive mineral',
    pickTitle: 'Vehicles at your site',
    pickBody: 'Select the vehicle in front of you, or scan its permit.',
    noArrivals: 'No vehicles waiting',
    noArrivalsBody: 'Vehicles that have arrived at your sites will appear here to be received.',
    scanTitle: 'Scan the transport permit',
    scanBody: 'Point the camera at the QR code printed on the DigiTP or enter the OTP sent by SMS.',
    scanAction: 'Scan QR code',
    enterManually: 'Enter OTP instead',
    etpLabel: 'OTP',
    etpHint: 'The 6-digit code sent to the phone for this delivery.',
    verifyAction: 'Verify OTP',
    validateTitle: 'Transaction verified',
    validateFailedTitle: 'Verification failed',
    validateBody: 'This load matches the permit, the vehicle and this destination.',
    validateFailedBody:
      'Do not offload. Check the permit against the vehicle, and report the issue.',
    reportIssue: 'Report issue',
    scanAgain: 'Scan again',
    reviewTitle: 'Dispatched quantity',
    reviewBody: 'This is what the source recorded when the vehicle left.',
    weighNow: 'Enter received quantity',
    quantityTitle: 'What actually arrived?',
    quantityBody: 'Enter the quantity measured at your site.',
    receivedLabel: 'Received quantity',
    dispatched: 'Dispatched',
    received: 'Received',
    difference: 'Difference',
    matches: 'Received quantity matches dispatch.',
    shortage: 'Shortage',
    excess: 'Excess',
    reasonLabel: 'Reason for the difference',
    reasonPlaceholder: 'Select a reason',
    remarksLabel: 'Remarks',
    remarksPlaceholder: 'How and where the quantity was measured',
    confirmAction: 'Confirm receipt',
    confirmTitle: 'Confirm receipt?',
    confirmBody: 'This records the received quantity and updates your inventory.',
    confirmBodyDiscrepancy:
      'A difference will be recorded against this delivery. This updates your inventory.',
    confirming: 'Recording…',
    doneTitle: 'Receipt confirmed',
    doneBody: 'Inventory has been updated.',
    nowAvailable: 'Now available',
    viewDelivery: 'View delivery',
    backHome: 'Back to home',
    reason: {
      TRANSIT_LOSS: 'Loss in transit',
      MEASUREMENT_DIFFERENCE: 'Measurement difference',
      PARTIAL_OFFLOAD: 'Partial offload',
      OTHER: 'Other',
    },
  },

  /** Inventory and consumption. Received − Consumed = Available. */
  inventory: {
    title: 'Inventory',
    received: 'Received',
    consumed: 'Consumed',
    available: 'Available',
    thisPackage: 'This package',
    allPackages: 'All packages',
    noStock: 'No inventory yet',
    noStockBody: 'Mineral you receive will appear here, ready to draw down as you use it.',
    noStockInScope: 'Nothing held for this package',
    noStockInScopeBody: 'Receive a delivery against this package and it will appear here.',
    balanceTitle: 'Mineral balance',
    lastUpdated: 'Last updated',
    recordConsumption: 'Record consumption',
    history: 'Consumption history',
    noHistory: 'Nothing recorded yet',
    noHistoryBody: 'Consumption you record will be listed here.',
    fullyConsumed: 'Fully consumed',
  },

  consumption: {
    sheetTitle: 'Record consumption',
    sheetBody: 'Enter the quantity used. This draws down the available balance.',
    quantityLabel: 'Quantity used',
    purposeLabel: 'Used for',
    purposePlaceholder: 'Where or what it was used on',
    remainingAfter: 'Remaining after this',
    record: 'Record',
    recording: 'Recording…',
    recorded: 'Consumption recorded',
    availableNow: 'Available',
  },

  /** Temporary Excavation — ORGANIZATION ONLY. The single application type. */
  excavation: {
    title: 'Temporary excavation',
    newApplication: 'New application',
    active: 'Active applications',
    needsAttention: 'Needing attention',
    noApplications: 'No applications yet',
    noApplicationsBody:
      'Apply for temporary excavation when you need to extract mineral from your own site.',
    queryTitle: 'The department has raised a query',
    queryBody: 'Respond through the Mahakhanij portal to continue the review.',
    responseNote:
      'Responding to a query is handled outside this app. Contact the department to continue.',
    submitDraft: 'Submit application',
    submitting: 'Submitting…',
    submitTitle: 'Submit this application?',
    submitBody: 'Once submitted it goes to the department for review and cannot be edited here.',
    site: 'Site',
    surveyNumber: 'Survey number',
    area: 'Area',
    depth: 'Depth',
    excavationDetails: 'Excavation',
    mineral: 'Mineral',
    estimatedQuantity: 'Estimated quantity',
    purpose: 'Purpose',
    period: 'Period',
    from: 'From',
    to: 'To',
    documents: 'Documents',
    noDocuments: 'No documents attached',
    attachDocument: 'Attach document',
    documentType: 'Document type',
    submittedOn: 'Submitted on',
    lastUpdated: 'Last updated',
    saveDraft: 'Save as draft',
    reviewTitle: 'Review and pay',
    applicant: 'Applicant',
    applicationFee: 'Application fee',
    feeNote: 'The application is submitted automatically once the fee is paid.',
    payAndSubmit: 'Pay & submit',
    demandNoteTitle: 'Demand note issued',
    demandNoteBody:
      'Pay the demand note to receive your excavation order. The order is issued as soon as the payment succeeds.',
    demandNoteNumber: 'Demand note',
    dueBy: 'Due by',
    payDemandNote: 'Pay demand note',
    orderTitle: 'Excavation order',
    orderNumber: 'Order number',
    orderValidFrom: 'Valid from',
    orderValidUntil: 'Valid until',
    permittedQuantity: 'Permitted quantity',
    downloadOrder: 'Download order',
    payments: 'Payments',
    noPayments: 'No payments yet',
    awaitingFee: 'Application fee not yet paid',
    awaitingFeeBody: 'This application has not been submitted. Pay the fee to send it for review.',
    /* The five steps, in the order the web application form asks them. */
    stepApplicant: 'Who is applying?',
    stepApplicantHint: 'Pre-filled from your account. Correct anything that has changed.',
    stepExcavation: 'What will you extract?',
    stepExcavationHint: 'Mineral, quantity, method and the period you need.',
    stepLocation: 'Where is the quarry?',
    stepLocationHint: 'Pick the village, give the survey number, and mark the site on the map.',
    stepDocuments: 'What are you attaching?',
    stepDocumentsHint: 'The department needs these before it can review the application.',
    stepReview: 'Check and confirm',
    stepReviewHint: 'Read it back before you pay. Nothing is submitted until the fee is paid.',

    /* 1 · Applicant */
    applicantName: 'Full name',
    applicantMobile: 'Mobile number',
    applicantEmail: 'Email',
    applicantEmailHint: 'The department sends the demand note here.',
    idProof: 'ID proof',
    idProofNumber: 'ID number',
    alternatePhone: 'Alternate phone',
    registeredAddress: 'Registered address',
    idProofTypes: {
      AADHAAR: 'Aadhaar',
      PAN: 'PAN',
      VOTER_ID: 'Voter ID',
      DRIVING_LICENCE: 'Driving licence',
    },

    /* 2 · Excavation */
    excavationMethod: 'Excavation method',
    excavationMethods: {
      MANUAL: 'Manual',
      SEMI_MECHANISED: 'Semi-mechanised',
      MECHANISED: 'Mechanised',
    },
    remarks: 'Remarks',
    remarksHint: 'Anything the reviewing officer should know. Optional.',

    /* 3 · Quarry and location */
    district: 'District',
    taluka: 'Taluka',
    village: 'Village',
    subDivisionNumber: 'Sub-division (hissa)',
    landType: 'Land type',
    landTypes: {
      PRIVATE: 'Private',
      GOVERNMENT: 'Government',
      GRAM_PANCHAYAT: 'Gram panchayat',
      FOREST: 'Forest',
      OTHER: 'Other',
    },
    siteAddressLabel: 'Site address',
    pincode: 'PIN code',
    markOnMap: 'Mark the excavation site',
    markOnMapHint: 'Tap the map to place the pin, or use your current location.',
    useCurrentLocation: 'Use my current location',
    locatingYou: 'Finding you…',
    locationDenied: 'Location permission was refused. Tap the map to place the pin instead.',
    locationUnavailable: 'Your location could not be found. Tap the map to place the pin instead.',
    pinPlaced: 'Site marked',
    noPinYet: 'No pin placed yet',
    suggestedFromPin: 'Suggested from the pin',
    applySuggestion: 'Use this',
    coordinates: 'Coordinates',

    /* 4 · Documents */
    documentChecklist: 'Required documents',
    documentsAttached: 'attached',
    required: 'Required',
    optional: 'Optional',
    attach: 'Attach',
    replace: 'Replace',
    remove: 'Remove',
    documentsMissing: 'Attach every required document to continue.',
    attachmentSimulated: 'Attachment is simulated in this prototype.',

    /* 5 · Review */
    declaration: 'Declaration',
    declarationText:
      'I declare that the information given above is true to the best of my knowledge, and that excavation will stay within the quantity, area and depth applied for.',
    editStep: 'Edit',
    paymentSummary: 'Payment summary',
    applicationInformation: 'Application information',
    whatHappensNext: 'What happens next',
    nextStepReview: 'The department reviews your application and may raise a query.',
    nextStepDemandNote: 'If it is cleared, a demand note is issued for you to pay.',
    nextStepOrder: 'Paying the demand note issues your excavation order.',
    createdTitle: 'Application submitted',
    createdBody: 'The department will review it and update the status here.',
    draftedTitle: 'Draft saved',
    draftedBody: 'You can finish and submit it whenever you are ready.',
    viewApplication: 'View application',
    docTypes: {
      SITE_PLAN: 'Site plan',
      LAND_RECORD: 'Land record (7/12 extract)',
      LAND_OWNER_CONSENT: 'Land owner consent',
      IDENTITY_PROOF: 'Identity proof',
      ENVIRONMENTAL_CLEARANCE: 'Environmental clearance',
      OTHER: 'Other document',
    },
  },

  /** Payments — application fee before submission, demand note before order. */
  payment: {
    title: 'Payment',
    summary: 'Payment summary',
    payableNow: 'Payable now',
    proceed: 'Proceed to pay',
    redirectingTitle: 'Redirecting to secure payment gateway',
    redirectingBody:
      'You will not be charged until you confirm on the gateway. Do not close this screen.',
    doNotClose: 'Do not press back or close the app',
    successTitle: 'Payment successful',
    receipt: 'Receipt number',
    reference: 'Gateway reference',
    method: 'Paid using',
    paidOn: 'Paid on',
    failedTitle: 'Payment failed',
    failedBody: 'No money has been taken. You can try again.',
    tryAgain: 'Try again',
    cancel: 'Cancel payment',
    applicationFee: 'Application fee',
    demandNote: 'Demand note',
    whatNext: 'What happens next',
    nextAfterFee:
      'Your application goes to the department for review. If it is approved a demand note is raised, and paying that issues your excavation order.',
    nextAfterDemandNote: 'Your excavation order has been issued and is available on this application.',
    viewApplication: 'View application',
    simulateFailure: 'Simulate a failed payment',
  },

  /** Authentication — Splash → Login/Register → Mobile → OTP → Experience. */
  auth: {
    welcomeTitle: 'Mineral, from source to site',
    welcomeBody:
      'Find a stock point, raise an enquiry, track the vehicle, verify what arrives, and manage what you use.',
    signIn: 'Sign in',
    createAccount: 'Create account',

    mobileLabel: 'Mobile number',
    mobilePlaceholder: '10-digit number',
    mobileHint: 'We will send a 6-digit verification code to this number.',
    mobileInvalid: 'Enter a valid 10-digit Indian mobile number.',

    verifyTitle: 'Verify your number',
    verifySentTo: 'Enter the 6-digit code sent to',
    changeNumber: 'Change',
    resendIn: 'Resend code in',
    resend: 'Resend code',
    resent: 'A new code has been sent.',
    otpInvalid: 'That code is not correct. Please try again.',
    noAccount: 'No account exists for this number.',
    alreadyRegistered: 'An account already exists for this number.',

    registerTitle: 'Create account',
    userTypeQuestion: 'How will you use Mahakhanij?',
    userTypeHelp: 'This decides what the app shows you. It cannot be changed later.',
    individualTab: 'Individual',
    organizationTab: 'Organization',
    consumerSummary: 'For an individual buying mineral for personal use.',
    organizationSummary:
      'For a builder, contractor, government body or any other organization working across projects and packages.',

    stepDetailsTitle: 'Basic & Address details',
    stepKycTitle: 'KYC Verification',
    stepDetailsHelpIndividual: 'Enter your personal contact and delivery destination details.',
    stepDetailsHelpOrganization: 'Enter authorized representative, entity and registered office details.',

    detailsTitle: 'Your details',
    fullNameLabel: 'Full name',
    repFullNameLabel: 'Authorized person full name',

    organizationTitle: 'Organization details',
    organizationNameLabel: 'Organization name',
    organizationTypeLabel: 'Organization type',
    organizationTypeHint: 'Every organization type uses the same experience.',
    registrationNumberLabel: 'Mahakhanij registration number (optional)',

    deliveryTitle: 'Where should mineral be delivered?',
    deliveryHelp: 'Used to find nearby stock points and to verify deliveries on arrival.',
    addressLabel: 'Address (House / Flat / Street / Area)',
    orgAddressLabel: 'Registered office / site address',
    talukaLabel: 'Taluka',
    districtLabel: 'District',
    pincodeLabel: 'PIN code',
    pincodeInvalid: 'Enter a valid 6-digit PIN code.',

    // KYC Verification strings
    kycTitleIndividual: 'Individual KYC Verification',
    kycDescIndividual: 'Verify identity via Aadhaar. An OTP will be sent to your Aadhaar-linked mobile number.',
    kycTitleOrganization: 'Organization KYC Verification',
    kycDescOrganization: 'Verify entity via PAN. An OTP will be sent to your PAN-registered mobile number.',

    aadhaarLabel: 'Aadhaar card number',
    aadhaarPlaceholder: '12-digit Aadhaar number',
    aadhaarInvalid: 'Enter a valid 12-digit Aadhaar number.',
    uploadAadhaarLabel: 'Upload Aadhaar Card',
    uploadAadhaarHint: 'Front or combined copy of Aadhaar card',

    panLabel: 'Organization PAN number',
    panPlaceholder: '10-character PAN (e.g. ABCDE1234F)',
    panInvalid: 'Enter a valid 10-character PAN (e.g. ABCDE1234F).',
    uploadPanLabel: 'Upload Organization PAN Card',
    uploadPanHint: 'Clear copy of entity PAN card',

    kycDocRequired: 'Please upload the required KYC document to continue.',
    kycNoticeIndividual: 'A secure 6-digit OTP will be dispatched to your Aadhaar-linked mobile number for UIDAI verification.',
    kycNoticeOrganization: 'A secure 6-digit OTP will be dispatched to the authorized mobile number registered with this Aadhaar.',
    verifyAndSendOtp: 'Verify & Send OTP',
    continueToKyc: 'Continue to KYC Verification',

    verifyAadhaarTitle: 'Verify Aadhaar OTP',
    verifyPanTitle: 'Verify Signatory Aadhaar OTP',
    verifyAadhaarSentTo: 'Enter the 6-digit OTP sent to your Aadhaar-linked mobile number',
    verifyPanSentTo: 'Enter the 6-digit OTP sent to the authorized mobile number registered with Aadhaar',

    required: 'This field is required.',
    haveAccount: 'Already have an account?',
    noAccountYet: 'New to Mahakhanij?',
  },

  /** PROTOTYPE-ONLY copy. Delete alongside @/prototype. */
  prototype: {
    banner: 'Prototype',
    choosePersona: 'Choose a persona',
    personaIntro:
      'A review shortcut that skips authentication. The real sign-in flow is on the entry screen.',
    switchPersona: 'Switch persona',
    demoSection: 'Prototype controls',
    notBuiltYet: 'Not built yet',
    otpHint: 'Prototype — the code is 123456. Any other code shows the error state.',
    seededAccounts: 'Seeded accounts: 9822014576 (Organization) · 9730845120 (Individual)',
  },
} as const;

/** Shape that every future locale file must satisfy. */
export type Copy = typeof en;
